# Generated by Django 5.2.7 on 2025-11-25 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(help_text="Describe your project in detail. Example: 'We are building a mobile app for farmers to track crops. Our target is to reach 500 users in 6 months...'"),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_amount',
            field=models.PositiveIntegerField(help_text='Target amount in EGP (Egyptian Pounds)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
